version: "2.1"
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            database: auror
            port: 5432
            user: auror
            password: auror
            migrations: false
            schema: public
  postgres:
    image: postgres:10.5
    restart: always
    healthcheck:
      test: "!</dev/tcp/db/5432"
    environment:
      POSTGRES_USER: auror
      POSTGRES_PASSWORD: auror
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
